// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDen1mARLC0z9gO3J_RjP2DpNthAQzr0BM',
    appId: '1:410760664572:web:b98f5127e01bce8dddce79',
    messagingSenderId: '410760664572',
    projectId: 'todo-provider-a897c',
    authDomain: 'todo-provider-a897c.firebaseapp.com',
    storageBucket: 'todo-provider-a897c.firebasestorage.app',
    measurementId: 'G-F4PFESBL7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo05x1bz6gtlWfdDT44CGYEcFyYXlp0r0',
    appId: '1:410760664572:android:edd7bd4764d83ae3ddce79',
    messagingSenderId: '410760664572',
    projectId: 'todo-provider-a897c',
    storageBucket: 'todo-provider-a897c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAn5J0HqFPcyZT3ngBMGkyYQWpzUc92mo',
    appId: '1:410760664572:ios:dacd4252ed9e74fdddce79',
    messagingSenderId: '410760664572',
    projectId: 'todo-provider-a897c',
    storageBucket: 'todo-provider-a897c.firebasestorage.app',
    iosBundleId: 'com.example.providerTodoApp',
  );
}
