import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider_todo_app/providers/app_provider.dart';
import 'package:provider_todo_app/services/firebase_options.dart';
// generated by FlutterFire CLI

Future<void> main() async {  
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform);
  runApp(const AppProviders(
      
  ));
}
