import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider_todo_app/providers/app_provider.dart';
import 'package:provider_todo_app/services/firebase_options.dart';
// generated by FlutterFire CLI

Future<void> main() async {  
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform);
  runApp(const AppProviders(
      
  ));
}
<<<<<<< HEAD

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        
        colorScheme: .fromSeed(seedColor: Colors.deepPurple),
      ),
      
      //home: const LoginScreen(),
    );
  }
}

=======
>>>>>>> auth
